### ISSUE TITLE
Will APAlyzer work for paired-end reads?

### ISSUE THREAD

**Issue by lsoles** [RJWANGbioinfo/APAlyzer#3]
Thanks for this program! I have been trying to use APAlyzer to analyze paired-end RNA-seq, but it doesn't seem to be working. Does the current build allow for analysis of paired-end reads? Thank you!

**Comment by RJWANGbioinfo** [comment]
Hi @lsoles ,

The support of pair-end will be added into the next major update.
Current you can extract 3' read of each read pair in your bam, and use it as the input of APAlyzer

**Comment by shorthouse-mrc** [comment]
Hi @RJWANGbioinfo - thanks for the hard work on this tool! I just wanted to add to the discussion on paired-end reads. 

For now i've managed to get the tool working on paired-end data by aligning only the first fastq files prior to running APAlyzer on the resultant .bam. 

Before this I attempted to extract only the forward/reverse reads from the paired-aligned .bam files using $samtools view with the -F 20 or -f 16 flags, but the PASEXP_IPA step requiring featurecounts errored due to paired end reads being detected. 

I wanted to ask - is this an appropriate way of running the analysis for paired-end reads, or would you recommend a different approach? Thanks!

**Comment by RJWANGbioinfo** [comment]
Hi @shorthouse-mrc ,

Thanks for your feedback, we just added a proc `ThreeMostPairBam` in the dev version (1.5.5) of APAlyzer. Our tester @zoomzoom1011 is currently running the internal testing on that.  If you don't mind waiting a bit, we will soon push this proc into Bioconductor when it's ready.  Alternatively, if you don't want to wait, you can also give it a try (may not be stable at the current stage) by yourself.  Here are the guidelines of the proc:

1. How to get the dev version of APAlyzer:

`BiocManager::install('RJWANGbioinfo/APAlyzer')`

2. How to use this new proc in R:

```
Bamfile='path_to_inputdir/input.bam'
Outdir='path_to_outdir/'  
StrandType="forward-reverse"    ## "forward-reverse",  or "reverse-forward" or "NONE"
ThreeMostPairBam(BamfilePath= Bamfile , OutDirPath= Outdir , StrandType= StrandType)
```

3. Output of this new proc:  

_A bam file named as *.3most.bam located in `Outdir`._

**Comment by RJWANGbioinfo** [comment]
Hi @lsoles and @shorthouse-mrc , we have added the proc `ThreeMostPairBam` into v1.5.5, and pushed this version into the [APAlyzer Dev of Bioconductor](https://www.bioconductor.org/packages/devel/bioc/html/APAlyzer.html) (may take 24-48 hrs to take effect) .

**Comment by shorthouse-mrc** [comment]
Hi @RJWANGbioinfo  - thanks so much for this. I've tested on my available data, and it seems to have worked (It has produced output that makes biological sense!). 

Thanks again for your work on this.

**Comment by RJWANGbioinfo** [comment]
np ^.^.
